name: clockin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#1E88E5"
  image: assets/logo.png

  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
